'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const O=require('../src/optics.js');
const close=(a,b,tol=1e-5)=>assert.ok(Math.abs(a-b)<=tol*Math.max(1,Math.abs(b)),`${a} != ${b}`);
const sum=a=>a.reduce((s,v)=>s+v,0);
const base={...O.defaults,width:40,height:30,shape:'rect',layout:'manual',manual:[[0,0,0]],pattern:'solid',color1:'#ffffff',quality:160,aperture:1,gap:10,spread:0,roi:0};
let solver=new O.Solver();
test('FFT forward/inverse round trip',()=>{let re=Float32Array.from({length:256},(_,i)=>Math.sin(i*.37)),im=new Float32Array(256),original=new Float32Array(re);O.fft2(re,im,16,16);O.fft2(re,im,16,16,true);re.forEach((v,i)=>close(v,original[i],2e-5));});
test('Kernel inverse square on axis',()=>{close(O.kernelValue(0,0,10,1),10000);close(O.kernelValue(0,0,10,1)/O.kernelValue(0,0,20,1),4);});
test('Lambertian off-axis geometry includes both cosines',()=>close(O.kernelValue(10,0,10,1),2500));
test('Angular exponent matches half-maximum convention',()=>{for(const a of [60,90,120,150]){const m=-Math.log(2)/Math.log(Math.cos(a*Math.PI/360));close(Math.cos(a*Math.PI/360)**m,.5);}});
test('FFT convolution matches direct sum, with no wraparound',()=>{let nx=16,ny=12,k=O.makeKernel(nx,ny,1,1,5,120),re=new Float32Array(k.re.length),im=new Float32Array(k.re.length);re[3*k.w+4]=.8;re[10*k.w+14]=.2;O.fft2(re,im,k.w,k.h);for(let i=0;i<re.length;i++){const a=re[i],b=im[i];re[i]=a*k.re[i]-b*k.im[i];im[i]=a*k.im[i]+b*k.re[i];}O.fft2(re,im,k.w,k.h,true);for(let y=0;y<ny;y++)for(let x=0;x<nx;x++)close(re[y*k.w+x],.8*O.kernelValue(x-4,y-3,5,1)+.2*O.kernelValue(x-14,y-10,5,1),2e-5);});
test('Finite emitter deposition conserves per-channel normal intensity',()=>{const s=O.normalize(base),leds=O.makeLEDs(s).leds,r=O.rasterSources(s,leds,160,120,.25,.25);[s.mcdR,s.mcdG,s.mcdB].forEach((v,c)=>close(sum(r.src[c]),v/1000*s.brightness/100,1e-7));});
test('Separated RGB apertures conserve normal intensity',()=>{const s=O.normalize({...base,splitRGB:true}),leds=O.makeLEDs(s).leds,r=O.rasterSources(s,leds,160,120,.25,.25);[s.mcdR,s.mcdG,s.mcdB].forEach((v,c)=>close(sum(r.src[c]),v/1000*s.brightness/100,1e-7));});
test('sRGB round trip',()=>{for(const v of [0,.001,.03,.04,.18,.5,1])close(O.linearToSrgb(O.srgbToLinear(v)),v,1e-10);});
test('ARGB alpha is tint strength, not optical throughput',()=>{assert.deepEqual(O.getFilter('#00FF0000'),[1,1,1]);assert.deepEqual(O.getFilter('#FFFF0000'),[1,0,0]);});
test('Zero transmission produces exactly zero emitted luminance',()=>{let r=solver.solve({...base,transmission:0});for(const f of r.fields)assert.ok(f.every(v=>v===0));assert.equal(r.stats.robust,null);});
test('Zero LED output produces a black display in a dark room',()=>{let r=solver.solve({...base,brightness:0});assert.equal(r.stats.mean,0);let img=O.rgba(r);assert.ok(img.every((v,i)=>i%4===3||v===0));});
test('Doubling PWM doubles untonemapped luminance',()=>{let a=solver.solve({...base,brightness:10}),b=solver.solve({...base,brightness:20});close(b.stats.mean/a.stats.mean,2,2e-6);});
test('Halving transmission halves luminance',()=>{let a=solver.solve({...base,transmission:80}),b=solver.solve({...base,transmission:40});close(b.stats.mean/a.stats.mean,.5,2e-6);});
test('Red transmission filter removes G/B components',()=>{const r=solver.solve({...base,argb:'#FFFF0000'});assert.ok(r.fields[1].every(v=>v===0));assert.ok(r.fields[2].every(v=>v===0));assert.ok(r.stats.mean>0);});
test('Exposure does not change physical statistics',()=>{const a=solver.solve({...base,exposure:-3}),b=solver.solve({...base,exposure:3});close(a.stats.mean,b.stats.mean,1e-10);});
test('Symmetric source and sheet produce a symmetric field',()=>{const r=solver.solve(base),f=r.fields[1];for(let y=0;y<r.ny;y++)for(let x=0;x<r.nx;x++)close(f[y*r.nx+x],f[(r.ny-1-y)*r.nx+r.nx-1-x],1e-5);});
test('Increased distance lowers isolated LED peak',()=>{const a=solver.solve({...base,gap:5}),b=solver.solve({...base,gap:20});assert.ok(b.stats.max<a.stats.max);});
test('Diffuser blur does not create net diffuse output',()=>{const a=solver.solve({...base,spread:0}),b=solver.solve({...base,spread:1});assert.ok(b.fields.reduce((s,f)=>s+sum(f),0)<=a.fields.reduce((s,f)=>s+sum(f),0)*(1+1e-6));});
test('Ring mask leaves the central aperture empty',()=>{const r=solver.solve({...base,shape:'ring',width:40,height:40,layout:'ring',inset:4,hole:.5,density:150,roi:1});const i=Math.floor(r.ny/2)*r.nx+Math.floor(r.nx/2);assert.equal(r.mask[i],0);for(const f of r.fields)assert.equal(f[i],0);});
test('Empty ROI falls back to full sheet and matches exported mask',()=>{const r=solver.solve({...base,roi:500});assert.equal(r.stats.validROI,false);assert.deepEqual(r.roiMask,r.mask);});
test('Empty LED list is a valid zero-light result',()=>{const r=solver.solve({...base,manual:[]});assert.equal(r.leds.length,0);assert.equal(r.stats.mean,0);assert.ok(r.warnings.length>0);});
test('Manual coordinates are sanitized and known keys only retained',()=>{const s=O.normalize({width:100,manual:[[Infinity,1],[1000,1000],[1,2]],junk:'x'});assert.equal(s.manual.length,2);assert.equal(s.manual[0][0],50);assert.equal('junk' in s,false);});
test('Overlarge LED layouts fail rather than silently truncate',()=>{assert.throws(()=>O.makeLEDs(O.normalize({...base,layout:'grid',width:2000,height:2000,density:1000})),/多|超/);});
test('Polygon rejects too few points',()=>assert.throws(()=>O.shapeInfo(O.normalize({...base,shape:'polygon',polygon:'0,0\n100,100'})),/3点/));

test('Narrow beam and maximum gap remain finite',()=>{const m=-Math.log(2)/Math.log(Math.cos(10*Math.PI/360));for(const x of [0,100,2000])assert.ok(Number.isFinite(O.kernelValue(x,10,300,m)));close(O.kernelValue(0,0,300,m),1e6/90000);});
